name: Deploy Staging Server
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: 0916dhkim/discord-bot-beef-stroganoff:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  deploy:
    needs: docker
    runs-on: ubuntu-latest
    env:
      SSH_USER: ${{ secrets.STAGING_SSH_USER }}
      SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
      SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}
      REMOTE_DOCKER_PORT: 2374
      DOCKER_HOST: 127.0.0.1:2374
    steps:
      - uses: actions/checkout@master
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
      - name: Tunnel SSH
        run: ssh -fNL $DOCKER_HOST:localhost:$REMOTE_DOCKER_PORT staging
      - name: Create secret
        run: echo ${{ secrets.DISCORD_TOKEN }} | docker secret create discord-bot-beef-stroganoff.token -
      - name: Run bot
        run: docker stack deploy -c docker-compose.deploy.yml discord-bot-beef-stroganoff
